extends:
  file: ../pipeline.yaml
agent:
  image: denispalnitskyaurea/pythonextended
pipelines:
  pullRequest:
    build:
      steps:            
      - sh: pytest --cov
        name: python-unit-test    
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION) 
        name: tag-version

    build:
      steps:                  
      - sh:  pytest --cov
        name: python-unit-test
      - sh:  coveralls
        name: pubish-coverage-to-coveralls
      - sh: jx step stash -c tests -p "target/test-reports/*" --verbose
        name: stash-test-results