extends:
  file: ../pipeline.yaml
agent:
  image: denispalnitskyaurea/pythonextended
pipelines:
  pullRequest:
    build:
      steps:            
      - sh: pytest --cov
        name: python-unit-test
    postBuild:
      steps:
      - sh: export NEXUS_CENTRAL_USERNAME=\$(jx step credential -s central_nexus -k username -n jx)
      - sh: export NEXUS_CENTRAL_PASSWORD=\$(jx step credential -s central_nexus -k password -n jx)
      - sh: export NEXUS_CENTRAL_ENDPOINT=\$(jx step credential -s central_nexus -k endpoint -n jx)
      - sh: cd .. && export NEXUS_CENTRAL_ENDPOINT=\$(jx step credential -s \$REPO_OWNER-\$REPO_NAME -n jx -k repo)
        name: expose nexus secrets
      - sh: cd .. && tar --exclude=\$REPO_OWNER-\$REPO_NAME/.git -cvzf \$REPO_OWNER-\$REPO_NAME-\$BRANCH_NAME-\$BUILD_NUMBER.tar.gz \$REPO_OWNER-\$REPO_NAME && cd \$REPO_OWNER-\$REPO_NAME
        name: package-artifacts
        comment: Packaging artifacts as a tar file
      - sh: cd .. && curl -v -u \$NEXUS_CENTRAL_USERNAME:\$NEXUS_CENTRAL_PASSWORD --upload-file \$(basename \$OLDPWD)-\$BRANCH_NAME-\$BUILD_NUMBER.tar.gz \$NEXUS_CENTRAL_ENDPOINT/repository/\$(basename \$OLDPWD)/\$(basename \$OLDPWD)-\$BRANCH_NAME-\$BUILD_NUMBER.tar.gz
        name: package-artifacts
        comment: Need to remove hard coded creds and read from ENV ?

  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION) 
        name: tag-version

    build:
      steps:                  
      - sh:  pytest --cov=tests
        name: python-unit-test
      - sh:  coveralls
        name: pubish-coverage-to-coveralls
      - sh: jx step stash --classifier tests -p "target/test-reports/*"
        name: stash-test-results