extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-python
  container: python
pipelines:
  pullRequest:
    build:
      steps:    
      - sh: python -m unittest
        name: python-unittest        
  release:    
    agent:
      image: sharepointoscar/node:8    
    # setVersion:
    #   steps:
    #   - sh: echo \$(jx-release-version) > VERSION
    #     name: next-version
    #     comment: so we can retrieve the version in later steps
    #   # TODO set the version in source?
    #   - sh: jx step tag --version \$(cat VERSION)
    #     name: tag-version
    build:
      steps:    
      - sh: node --version        
        name: NodeJs step
      # - sh: python -m unittest
      #   name: python-unittest        
